import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 현재 로그인된 유저의 정보 출력 - 서버컴포넌트이기에 터미널에 출력
  let result= await getServerSession(authOptions)
  console.log(result)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            NewForum
          </Link>
          <Link href="/list">List</Link>
          {/* JSX 안에서 if쓰고 싶으면 삼항연산자 */}
          {
            // 조건식?조건식이참일때:조건식거짓일때
            result?<span>{result.user.name}<LogoutBtn/></span>:<LoginBtn/>
          }
        </div>
        {children}
      </body>
    </html>
  );
}
